version: '3.1'

services:
  core-api:
  #  image: ghcr.io/programador-tv/dev-core-api
   container_name: core-api
   restart: always
   ports:
    - 9002:80
   build:
    context: ./src/
    dockerfile: ./WebApi/dockerfile.aspnet

  core-websocket:
  #  image: ghcr.io/programador-tv/dev-core-websocket
   container_name: core-websocket
   restart: always
   ports:
    - 9003:80
   build:
    context: ./src/
    dockerfile: ./WebSocket/dockerfile.aspnet

  core-background:
  #  image: ghcr.io/programador-tv/dev-core-background
   container_name: core-background
   restart: always
   build:
    context: ./src/
    dockerfile: ./Background/dockerfile.aspnet
