version: '3.1'

services:
  core-api:
   container_name: core-api
   restart: always
   ports:
    - 9002:8080
   build:
    context: ./src/
    dockerfile: ./WebApi/dockerfile.aspnet
   depends_on:
    - sqlserver
    - redis
   networks:
    - app-network

  core-websocket:
   container_name: core-websocket
   restart: always
   ports:
    - 9003:8080
   build:
    context: ./src/
    dockerfile: ./WebSocket/dockerfile.aspnet
   depends_on:
    - sqlserver
    - redis
   networks:
    - app-network

  core-background:
   container_name: core-background
   restart: always
   build:
    context: ./src/
    dockerfile: ./Background/dockerfile.aspnet
   depends_on:
    - sqlserver
    - redis
   networks:
    - app-network

  sqlserver:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: sqlserver
   restart: always
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=StrongPassword123!
    - MSSQL_PID=Developer
   volumes:
    - sqlserver-data:/var/opt/mssql
   networks:
    - app-network

  redis:
   image: redis:alpine
   container_name: redis
   restart: always
   command: redis-server --requirepass StrongRedisPassword123!
   volumes:
    - redis-data:/data
   networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:
  redis-data:


