version: '3.1'

services:
  core-api:
   container_name: core-api
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   ports:
    - 9002:8080
   build:
    context: ./src/
    dockerfile: ./WebApi/dockerfile.aspnet
   depends_on:
    - redis
   networks:
    - app-network

  core-websocket:
   container_name: core-websocket
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   ports:
    - 9003:8080
   build:
    context: ./src/
    dockerfile: ./WebSocket/dockerfile.aspnet
   depends_on:
    - redis
   networks:
    - app-network

  core-background:
   container_name: core-background
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   build:
    context: ./src/
    dockerfile: ./Background/dockerfile.aspnet
   depends_on:
    - redis
   networks:
    - app-network

  redis:
   image: redis:alpine
   container_name: redis
   restart: always
   command: redis-server --requirepass StrongRedisPassword123!
   volumes:
    - redis-data:/data
   networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:
  redis-data:


