services:
  core-api:
   image: ghcr.io/woolball-xyz/server-webapi:latest
   container_name: core-api
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   ports:
    - 9002:8080
   build:
    context: ./src/
    dockerfile: ./WebApi/dockerfile.aspnet
   volumes:
    - shared-data:/app/shared
   depends_on:
    - redis
   networks:
    - app-network

  core-websocket:
   image: ghcr.io/woolball-xyz/server-websocket:latest
   container_name: core-websocket
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   ports:
    - 9003:8080
   build:
    context: ./src/
    dockerfile: ./WebSocket/dockerfile.aspnet
   volumes:
    - shared-data:/app/shared
   depends_on:
    - redis
   networks:
    - app-network

  core-background:
   image: ghcr.io/woolball-xyz/server-background:latest
   container_name: core-background
   restart: always
   environment:
    - RedisConnection=redis:6379,password=StrongRedisPassword123!
   build:
    context: ./src/
    dockerfile: ./Background/dockerfile.aspnet
   volumes:
    - shared-data:/app/shared
   depends_on:
    - redis
   networks:
    - app-network

  redis:
   image: redis:alpine
   container_name: woolball-redis
   restart: always
   command: redis-server --requirepass StrongRedisPassword123!
   volumes:
    - redis-data:/data
   networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  shared-data:


