version: '3.8'

services:
  woolball-client:
    image: ghcr.io/woolball-xyz/client-node:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production 
      
  woolball-api:
    image: ghcr.io/woolball-xyz/server-webapi:latest
    container_name: core-api
    restart: always
    environment:
      - RedisConnection=${REDIS_CONNECTION}
    ports:
      - ${API_PORT}:8080
    volumes:
      - shared-data:/app/shared
    depends_on:
      - redis
    networks:
      - app-network

  woolball-websocket:
    image: ghcr.io/woolball-xyz/server-websocket:latest
    container_name: core-websocket
    restart: always
    environment:
      - RedisConnection=${REDIS_CONNECTION}
    ports:
      - ${WEBSOCKET_PORT}:8080
    volumes:
      - shared-data:/app/shared
    depends_on:
      - redis
    networks:
      - app-network

  woolball-background:
    image: ghcr.io/woolball-xyz/server-background:latest
    container_name: core-background
    restart: always
    environment:
      - RedisConnection=${REDIS_CONNECTION}
    volumes:
      - shared-data:/app/shared
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: woolball-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  shared-data: 